distributionUrl=file:///C:/Users/sepoa/.m2/wrapper/dists/apache-maven-3.9.6
distributionPath=wrapper/dists
zipStorePath=wrapper/dists
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar
