server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://devmariadb.sepoa.co.kr:3306/poasrm_restd?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: poasrm_restd
    password: poasrm_restd01
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
cors:
  allowed-origins:
    - http://localhost:5173
    - http://192.168.50.120:5173
    - https://sepoa-jsk.github.io

poa:
  admin-users:
    - admin
    - manager